[project]
name = "wukong"
version = "1.0.0"
authors = [
  { name="qiqilelebaobao", email="qiqilelebaobao@163.com" },
]
description = "Wukong is a program that helps parents flexibly generate test questions for their children. The tool is written in Python."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/qiqilelebaobao/wukong"
Issues = "https://github.com/qiqilelebaobao/wukong/issues"